/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { JwtResponseDTO, LoginCommand, RegisterCommand, UserDto } from ".././model";

/**
 * @summary Register a new user
 */
export const register = <TData = AxiosResponse<UserDto>>(
  registerCommand: RegisterCommand,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/auth/register`, registerCommand, options);
};
/**
 * @summary Authenticate user and get JWT token
 */
export const login = <TData = AxiosResponse<JwtResponseDTO>>(
  loginCommand: LoginCommand,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/auth/login`, loginCommand, options);
};
/**
 * @summary Get current user information
 */
export const getCurrentUser = <TData = AxiosResponse<UserDto>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.get(`/api/auth/me`, options);
};
export type RegisterResult = AxiosResponse<UserDto>;
export type LoginResult = AxiosResponse<JwtResponseDTO>;
export type GetCurrentUserResult = AxiosResponse<UserDto>;
