/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { Llmdto } from ".././model";

/**
 * Retrieves a list of all available Language Models in the system
 * @summary Get all available LLMs
 */
export const getLLMs = <TData = AxiosResponse<Llmdto>>(options?: AxiosRequestConfig): Promise<TData> => {
  return axios.get(`/api/llms`, options);
};
export type GetLLMsResult = AxiosResponse<Llmdto>;
