/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Response for API key operations
 */
export interface ApiKeyResponseDTO {
  /** Indicates if the user has an API key set */
  has_api_key: boolean;
}
