/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Request to set an OpenRouter API key
 */
export interface ApiKeyRequest {
  /**
   * The OpenRouter API key to set
   * @minLength 1
   */
  api_key: string;
}
