/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Base64 encoded avatar data with content type
 */
export interface AvatarRequest {
  /**
   * Base64 encoded image data
   * @minLength 1
   */
  data: string;
  /**
   * Content type of the image
   * @minLength 1
   * @pattern image/(png|jpeg)
   */
  content_type: string;
}
