/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Response confirming character avatar status
 */
export interface CharacterAvatarResponseDTO {
  /** Unique identifier for the character */
  id: number;
  /** Indicates if the character now has an avatar */
  has_avatar: boolean;
  /** New URL of the character's avatar image (null if avatar was removed or upload failed) */
  avatar_url?: string;
}
