/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

export interface CharacterDTO {
  id?: number;
  name?: string;
  short_description?: string;
  description?: string;
  has_avatar?: boolean;
  avatar_url?: string;
  is_global?: boolean;
  default_llm_id?: number;
  created_at?: string;
  updated_at?: string;
}
