/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Configuration for a character in a dialogue stream
 */
export interface CharacterConfigDto {
  /** ID of the character */
  character_id: number;
  /** ID of the language model to use for the character */
  llm_id: number;
}
