/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import type { CharacterDTO } from './characterDTO';

/**
 * Paginated list of characters
 */
export interface CharacterListDTO {
  /** List of characters on the current page */
  content: CharacterDTO[];
  /** Current page number (0-indexed) */
  page: number;
  /** Number of characters per page */
  size: number;
  /** Total number of characters across all pages */
  total_elements: number;
  /** Total number of pages */
  total_pages: number;
}
