/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Data Transfer Object for a Character with fields needed for dropdown selection
 */
export interface CharacterDropdownDTO {
  /** Unique identifier for the character */
  id: number;
  /** Name of the character */
  name: string;
  /** Indicates if the character is globally available */
  is_global: boolean;
  /** Indicates if the character has an avatar */
  has_avatar: boolean;
  /** URL of the character's avatar image (null if no avatar) */
  avatar_url?: string;
}
