/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Data Transfer Object for a Character
 */
export interface CharacterDTO {
  /** Unique identifier for the character */
  id: number;
  /** Name of the character */
  name: string;
  /** Brief character description */
  short_description: string;
  /** Detailed character description */
  description: string;
  /** Indicates if the character has an avatar */
  has_avatar: boolean;
  /** URL of the character's avatar image (null if no avatar) */
  avatar_url?: string;
  /** Indicates if the character is globally available */
  is_global: boolean;
  /** Default language model ID for this character (null if not set) */
  default_llm_id?: number;
  /** Timestamp when the character was created */
  created_at?: string;
  /** Timestamp when the character was last updated (null if never updated) */
  updated_at?: string;
}
