/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import type { CharacterDTO } from "./characterDTO";

export interface CharacterListDTO {
  content?: CharacterDTO[];
  page?: number;
  size?: number;
  total_elements?: number;
  total_pages?: number;
}
