/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Additional error details, specific to the error type
 */
export type ErrorResponseDTODetails = { [key: string]: { [key: string]: unknown } };
