/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import type { ErrorResponseDTODetails } from "./errorResponseDTODetails";

/**
 * Standard error response format
 */
export interface ErrorResponseDTO {
  /** Human-readable error message */
  message: string;
  /** Error code for programmatic handling */
  code: string;
  /** Additional error details, specific to the error type (optional) */
  details?: ErrorResponseDTODetails;
  /** Timestamp when the error occurred */
  timestamp?: string;
}
