/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

export type GetCharactersParams = {
  /**
   * Flag indicating whether to include global characters in the results
   */
  includeGlobal?: boolean;
  /**
   * Page number (0-based). Must be non-negative.
   */
  page?: number;
  /**
   * Number of items per page. Must be between 1 and 50.
   */
  size?: number;
};
