/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import type { UserDto } from "./userDto";

/**
 * Response containing JWT authentication details
 */
export interface JwtResponseDTO {
  /** JWT access token */
  access_token: string;
  /** Type of the token */
  token_type: string;
  /** Token expiration time in seconds */
  expires_in: number;
  /** User details associated with the token */
  user: UserDto;
}
