/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Command for user login
 */
export interface LoginCommand {
  /**
   * Username
   * @minLength 1
   */
  name: string;
  /**
   * Password
   * @minLength 1
   */
  password: string;
}
