/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import type { CharacterConfigDto } from "./characterConfigDto";

/**
 * Request to start a dialogue stream with real-time token generation
 */
export interface StartDialogueStreamRequest {
  /**
   * Description of the scene or context for the dialogue
   * @minLength 0
   * @maxLength 500
   */
  scene_description: string;
  /**
   * List of characters and their configurations for the dialogue (2-3 characters required)
   * @minLength 2
   * @maxLength 3
   * @minItems 2
   * @maxItems 3
   */
  character_configs: CharacterConfigDto[];
  /**
   * Number of turns in the dialogue (1-50)
   * @minimum 1
   * @maximum 50
   */
  length?: number;
}
