/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Command for updating an existing character
 */
export interface UpdateCharacterCommand {
  /**
   * Character name
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * Brief character description
   * @minLength 0
   * @maxLength 500
   */
  short_description: string;
  /**
   * Detailed character description
   * @minLength 0
   * @maxLength 5000
   */
  description: string;
  /** Default language model ID to use for this character */
  default_llm_id?: number;
}
