/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * PNG image file to use as avatar. Must be exactly 256x256 pixels and not exceed 1MB.
 */
export interface UploadAvatarCommand {
  /** PNG image file to use as avatar. Must be exactly 256x256 pixels and not exceed 1MB. */
  file: Blob;
}
