/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */

/**
 * Data Transfer Object for User information
 */
export interface UserDto {
  /** Unique identifier for the user */
  id: number;
  /** Username */
  name: string;
  /** Timestamp when the user was created */
  created_at?: string;
  /** Indicates if the user has an OpenRouter API key set */
  has_api_key: boolean;
}
