/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { ApiKeyRequest, ApiKeyResponseDTO } from ".././model";

/**
 * Checks if the authenticated user has an OpenRouter API key set
 * @summary Check API key status
 */
export const checkApiKeyStatus = <TData = AxiosResponse<ApiKeyResponseDTO>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/users/current/api-key`, options);
};
/**
 * Sets or updates the OpenRouter API key for the authenticated user
 * @summary Set or update OpenRouter API key
 */
export const setApiKey = <TData = AxiosResponse<ApiKeyResponseDTO>>(
  apiKeyRequest: ApiKeyRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.put(`/api/users/current/api-key`, apiKeyRequest, options);
};
/**
 * Deletes the OpenRouter API key for the authenticated user
 * @summary Delete OpenRouter API key
 */
export const deleteApiKey = <TData = AxiosResponse<ApiKeyResponseDTO>>(
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.delete(`/api/users/current/api-key`, options);
};
export type CheckApiKeyStatusResult = AxiosResponse<ApiKeyResponseDTO>;
export type SetApiKeyResult = AxiosResponse<ApiKeyResponseDTO>;
export type DeleteApiKeyResult = AxiosResponse<ApiKeyResponseDTO>;
