/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { StartDialogueStreamRequest } from ".././model";

/**
 * Starts real-time dialogue generation between characters using Server-Sent Events (SSE).
The client sends a scene description and character configurations, and the server
responds with a stream of events, including tokens generated by the characters in real-time.
Requires authentication with a valid API key.

 * @summary Stream dialogue generation
 */
export const streamDialogue = <TData = AxiosResponse<unknown>>(
  startDialogueStreamRequest: StartDialogueStreamRequest,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.post(`/api/dialogues/stream`, startDialogueStreamRequest, options);
};
export type StreamDialogueResult = AxiosResponse<unknown>;
