name: 'Setup Backend Environment'
description: 'Sets up Java environment for the backend'

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'
  distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  working-directory:
    description: 'Directory where the backend code is located'
    required: false
    default: './be/dailogi-server'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: maven 