/**
 * Generated by orval v7.8.0 🍺
 * Do not edit manually.
 * d-AI-logi API
 * API for d-AI-logi - an interactive web application for creating AI dialogues
 * OpenAPI spec version: v1.0.0
 */
import axios from "axios";
import type { AxiosRequestConfig, AxiosResponse } from "axios";

import type { CharacterAvatarResponseDTO, UploadAvatarCommand } from ".././model";

/**
 * Retrieves the avatar image for a specific character. Authentication is optional; unauthenticated users can access avatars for global characters.
 * @summary Get character avatar
 */
export const getAvatar = <TData = AxiosResponse<unknown>>(
  characterId: number,
  options?: AxiosRequestConfig
): Promise<TData> => {
  return axios.get(`/api/characters/${characterId}/avatar`, options);
};
/**
 * Uploads or replaces the avatar for a character. The character must be owned by the current user. Supports PNG and JPEG files up to 1MB and max 256x256 pixels. Requires authentication.
 * @summary Upload or update character avatar
 */
export const uploadAvatar = <TData = AxiosResponse<CharacterAvatarResponseDTO>>(
  characterId: number,
  uploadAvatarCommand: UploadAvatarCommand,
  options?: AxiosRequestConfig
): Promise<TData> => {
  const formData = new FormData();
  formData.append("file", uploadAvatarCommand.file);

  return axios.post(`/api/characters/${characterId}/avatar`, formData, options);
};
export type GetAvatarResult = AxiosResponse<unknown>;
export type UploadAvatarResult = AxiosResponse<CharacterAvatarResponseDTO>;
