spring:
  datasource:
    url: jdbc:postgresql://aws-0-eu-central-1.pooler.supabase.com:5432/postgres?user=dailogi_service.xrkinmlecfkesnfhpoak
    username: dailogi_service
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        default_schema: dail
  flyway:
    schemas: dail
    create-schemas: true
    default-schema: dail

# Swagger under reverse proxy
springdoc:
  swagger-ui:
    config-url: /server/v3/api-docs/swagger-config