spring:
  application:
    name: dailogi-server
  profiles:
    active: local
  jpa:
    open-in-view: false

# Swagger Documentation
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
