name: Main Branch Checks

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-tests:
    name: Run All Tests
    
    uses: ./.github/workflows/run-tests.yml
    secrets:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    with:
      artifact_retention_days: 7
    permissions:
      contents: read

  publish-summary:
    name: Publish Test Summary
    needs: run-tests
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download coverage artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
      
      - name: Generate summary
        run: |
          echo "# Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- Backend test coverage: ${{ needs.run-tests.outputs.backend_coverage || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
          echo "- Frontend test coverage: ${{ needs.run-tests.outputs.frontend_coverage || 'N/A' }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "For detailed reports, check the workflow artifacts." >> $GITHUB_STEP_SUMMARY 