name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.14.0
        cache: 'npm'
        cache-dependency-path: './ui/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run Vitest unit tests
      run: npm run test
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps chromium
    
    - name: Run Playwright E2E tests
      run: npm run test:e2e
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: ui/playwright-report/
        retention-days: 30
  
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be/dailogi-server
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Build and test with Maven
      run: mvn -B test

    - name: Generate JaCoCo Coverage Report
      run: mvn jacoco:report

    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: be/dailogi-server/target/site/jacoco/
        retention-days: 30 